create database mercado;
CREATE TABLE ESTOQUE(
	IDESTOQUE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(100),
    LUGAR VARCHAR(100)
);
CREATE TABLE PRODUTO (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
PRECO VARCHAR(30),
VALIDADE VARCHAR(50),
IDESTOQUE INT,
FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE(IDESTOQUE)
);

CREATE TABLE USUARIO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
EMAIL TEXT NOT NULL,
SENHA TEXT NOT NULL,
NOME TEXT NOT NULL
);

SELECT * FROM ESTOQUE;



SELECT * FROM PRODUTO;